name: Build Static Site

on:
  push:
    branches: [ main ]
defaults:
  run:
    working-directory: ./website

jobs:
  build:

    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [14.x]
    env:
      # Setting CI to empty string makes it so it will compile even with warnings
      CI: ""

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run build
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./website/build
        CLEAN: true
