name: Build and Run Tests

# Runs on pushes and pull requests targeting the default branch
on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./website
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          # Setup node doesn't use working directory
          cache-dependency-path: '**/package-lock.json'
      - name: Install Packages
        run: npm ci
      - name: Build Project
        run: npm run build --if-present
      - name: Run Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
